services:
  reverseproxy:
    container_name: nginxrp
    image: nginxrp
    volumes:
      - ./nginx/proxy.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    links:
      - django-app
      - flask-app
    
      
  django-app:
    container_name: django-app
    image: websocket
    ports:
      - "5555:5555"

  flask-app:
    image: flaskapp
    ports:
      - "5000:5000"
    container_name: flask-app

